version: 2

defaultenv: &defaultenv
  environment:
    SPLUNK_ADDR: https://localhost:8089
    SPLUNK_PASSWORD: test1234
    SPLUNK_START_ARGS: --accept-license

jobs:
  build:
    working_directory: /go/workdir/src/github.com/splunk/vault-plugin-splunk
    docker:
      - image: goboring/golang:1.15.3b5
        <<: *defaultenv
      - image: splunk/splunk:latest
        user: root
        <<: *defaultenv
    environment:
      - GOCACHE: /tmp/go/cache
    steps:
      - checkout
      - run:
          name: Code Quality
          command: make lint
      - run:
          name: Wait for Splunk Container
          command: |
            curl -4sSk --retry 40 --retry-connrefused --retry-delay 3 -o /dev/null ${SPLUNK_ADDR}
            sleep 5
            curl -4sSk --retry 40 --retry-connrefused --retry-delay 3 -o /dev/null ${SPLUNK_ADDR}
      - run:
          name: Test
          command: make test TESTREPORT=test-results/go/results.xml
      - run:
          name: Release
          command: |
            export GOVERSION=$(go version | awk '{sub("^go","",$3);print $3;}')
            [ -n "$CIRCLE_TAG" ] || tagargs="--snapshot"
            scripts/goreleaser --rm-dist $tagargs
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-results/
      - store_artifacts:
          path: dist/

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
